news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path('', include('newssj.urls')),
]

newssj/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField('Author rating', default=0)

    def update_rating(self):
        post_rating = self.post_set.aggregate(postRating=Sum('rating'))
        if post_rating.get('postRating') is None:
            p_rating = 0
        else:
            p_rating = 0
            p_rating += post_rating.get('postRating')

        comment_rating = self.user.comment_set.aggregate(commentRating=Sum('rating'))
        if comment_rating.get('commentRating') is None:
            c_rating = 0
        else:
            c_rating = 0
            c_rating += comment_rating.get('commentRating')

        comment_post_rating = 0
        for post in self.post_set.all():
            x = post.comment_set.aggregate(Sum('rating'))
            if x.get('rating__sum') is not None:
                print(x.get('rating__sum'))
                comment_post_rating += x.get('rating__sum')

        self.rating = p_rating * 3 + c_rating + comment_post_rating
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField('Category name', max_length=16, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):

    ARTICLE = 'AR'
    NEWS = 'NW'
    PUBLICATION_TYPE = (
        (ARTICLE, 'Статья'),
        (NEWS, 'Новость'),
    )
    # publication_type = models.CharField(max_length=2, choices=PUBLICATION_TYPE, default=ARTICLE)
    publication_type = models.CharField(max_length=2, choices=PUBLICATION_TYPE)
    post_title = models.CharField('Post name', max_length=256)
    time_in = models.DateTimeField('Post date', auto_now_add=True)
    category = models.ManyToManyField("Category", through='PostCategory',)
    post_text = models.TextField('Post text')
    rating = models.SmallIntegerField('Post rating', default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def preview(self):
        preview = self.post_text[:20] + '...'
        return preview

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def norm_date(self):
        return self.time_in.strftime('%d.%m.%Y')

    def __str__(self):
        return f'{self.post_title} : {self.post_text[0:20]}...'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField('Comment text', max_length=512)
    time_in = models.DateTimeField('Post date', auto_now_add=True)
    rating = models.SmallIntegerField('Comment rating', default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'{self.comment_text}'


class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='Subscriber',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='Subscriber',
    )

templates/news/create_post.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post create
{% endblock title %}

{% block content %}
<h1>Post</h1>
<hr>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
    </form>
{% endblock content %}

templates/news/news.html
{% extends 'flatpages/default.html' %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Все новости</h1>
<hr>
<div style="text-align: center;">
   {% if news %}


       <table>
           <tr>
               <td>Заголовок</td>
               <td>Статья</td>
               <td>Дата публикации</td>
{#               {% if perms.NewsSJ.change_post or perms.NewsSJ.delete_post %}#}
{#               <td>Действия</td>#}
{#               {% endif %}#}
           </tr>

           {% for new in news %}
           <tr>
               <td>{{ new.post_title }}</td>
               <td>{{ new.preview }}</td>
               <td>{{ new.norm_date }}</td>
{#           <td>#}
{#               {% if perms.simpleapp.change_product %}#}
{#               <a href="{% url 'edit_news' pk=post.id %}">Изменить</a>#}
{#               {% endif %}#}
{#               {% if perms.simpleapp.delete_product %}#}
{#               <a href="{% url 'delete_news' post.id %}">Удалить</a>#}
{#               {% endif %}#}
{#           </td>#}
           </tr>
           {% endfor %}
       </table>
   {% else %}
</div>

       <h2>Новостей нет!</h2>
   {% endif %}
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; первая</a>
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}

    <span class="current">
        Страница {{ page_obj.number }}
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
    {% endif %}
{% endblock content %}

templates/news/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
Пост
{% endblock title %}


{% block content %}
<h1>Детальная информация о новости {{post.id}}</h1>
Автор - {{ post.author.user }}
<br>
Время поста - {{ post.time_in }}
<br>
Тип поста - {{ post.publication_type }}
<br>
Заголовок - {{ post.post_title|censor }}
<br>
Текст - {{ post.post_text|censor }}
<br>
Рейтинг - {{ post.rating }}

{% endblock content %}

templates/news/post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1></h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/news/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

templates/news/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/news/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
Поиск
{% endblock title %}

{% block content %}
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
<hr>
   {% if news %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Статья</td>
           </tr>

           {% for new in news %}
           <tr>
               <td>{{ new.post_title }}</td>
               <td>{{ new.norm_date }}</td>
               <td>{{ new.preview }}</td>
           </tr>
           {% endfor %}
       </table>
   {% else %}

       <h2>Новостей нет!</h2>
   {% endif %}
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; первая</a>
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}

    <span class="current">
        Страница {{ page_obj.number }}
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
    {% endif %}

{% endblock content %}

templates/news/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}